# Generated by Django 2.2.7 on 2020-05-09 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200423_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Femelle', 'Female')], default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='locations',
            field=models.CharField(blank=True, choices=[('Alsace', 'Alsace'), ('Aquitaine', 'Aquitaine'), ('Auvergne', 'Auvergne'), ('Basse-Normandie', 'Basse-Normandie'), ('Bourgogne', 'Bourgogne'), ('Bretagne', 'Bretagne'), ('Centre', 'Centre'), ('Champagne-Ardenne', 'Champagne-Ardenne'), ('Corse', 'Corse'), ('Franche-Comté', 'Franche-Comté'), ('Haute-Normandie', 'Haute-Normandie'), ('Île-de-France', 'Île-de-France'), ('Languedoc-Roussillon', 'Languedoc-Roussillon'), ('Limousin', 'Limousin'), ('Lorraine', 'Lorraine'), ('Midi-Pyrénées', 'Midi-Pyrénées'), ('Nord-Pas-de-Calais', 'Nord-Pas-de-Calais'), ('Pays de la Loire', 'Pays de la Loire'), ('Picardie', 'Picardie'), ('Poitou-Charentes', 'Poitou-Charentes'), ("Provence-Alpes-Côte d'Azur", "Provence-Alpes-Côte d'Azur"), ('Rhône-Alpes', 'Rhône-Alpes'), ('Mayotte', 'Mayotte'), ('Martinique', 'Martinique'), ('Guadeloupe', 'Guadeloupe'), ('Reunion', 'Reunion'), ('Guyane', 'Guyane'), ('etranger', 'etranger')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='species',
            field=models.CharField(blank=True, choices=[('insectes', 'insectes'), ('mollusques', 'mollusques'), ('mammifères', 'mammifères'), ('oiseaux', 'oiseaux'), ('poissons', 'poissons'), ('amphibiens', 'amphibiens'), ('reptiles', 'reptiles'), ('plantes', 'plantes'), ('autres', 'autres')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Userapp',
        ),
    ]
